import { Injectable } from "@angular/core";
import { CountryModel } from "./model/CountryModel";

@Injectable({
 providedIn: "root"
})
export class IntlInputPhoneService {
 constructor() {}

 /**
  * Return the list of Countrymodel.
  */
 GetCountryList() {
    let CountryList: CountryModel[] = [];
    CountryList.push({ ISOCode: "AD", Name: "Andorra", FlagCssClass: "flag-ad", InputMasking: "999 999", CountryPhoneCode:"+376 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AE", Name: "United Arab Emirates", FlagCssClass: "flag-ae", InputMasking: "999 999 9999", CountryPhoneCode:"+971 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AF", Name: "Afghanistan", FlagCssClass: "flag-af", InputMasking: "999 999 9999", CountryPhoneCode:"+93 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AG", Name: "Antigua and Barbuda", FlagCssClass: "flag-ag", InputMasking: "999-9999", CountryPhoneCode:"+1 (268) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AI", Name: "Anguilla", FlagCssClass: "flag-ai", InputMasking: "999-9999", CountryPhoneCode:"+1 (264) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AL", Name: "Albania", FlagCssClass: "flag-al", InputMasking: "999 999 9999", CountryPhoneCode:"+355 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AM", Name: "Armenia", FlagCssClass: "flag-am", InputMasking: "999 999999", CountryPhoneCode:"+374 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AN", Name: "Netherlands Antilles", FlagCssClass: "flag-an", InputMasking: "999 9999", CountryPhoneCode:"+599 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AO", Name: "Angola", FlagCssClass: "flag-ao", InputMasking: "999 999 999", CountryPhoneCode:"+244 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AQ", Name: "Antarctica", FlagCssClass: "flag-aq", InputMasking: "9 99999", CountryPhoneCode:"+672 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AR", Name: "Argentina", FlagCssClass: "flag-ar", InputMasking: "999 99-9999-9999", CountryPhoneCode:"+54 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "AS", Name: "American Samoa", FlagCssClass: "flag-as", InputMasking: "999-9999", CountryPhoneCode:"+1 (684) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AT", Name: "Austria", FlagCssClass: "flag-at", InputMasking: "9999 999999", CountryPhoneCode:"+43 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AU", Name: "Australia", FlagCssClass: "flag-au", InputMasking: "9999 999 999", CountryPhoneCode:"+61 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AW", Name: "Aruba", FlagCssClass: "flag-aw", InputMasking: "999 9999", CountryPhoneCode:"+297 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "AZ", Name: "Azerbaijan", FlagCssClass: "flag-az", InputMasking: "999 999 99 99", CountryPhoneCode:"+994 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BA", Name: "Bosnia and Herzegovina", FlagCssClass: "flag-ba", InputMasking: "999 999 999", CountryPhoneCode:"+387 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BB", Name: "Barbados", FlagCssClass: "flag-bb", InputMasking: "999-9999", CountryPhoneCode:"+1 (246) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BD", Name: "Bangladesh", FlagCssClass: "flag-bd", InputMasking: "99999-999999", CountryPhoneCode:"+880 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BE", Name: "Belgium", FlagCssClass: "flag-be", InputMasking: "9999 99 99 99", CountryPhoneCode:"+32 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BF", Name: "Burkina Faso", FlagCssClass: "flag-bf", InputMasking: "99 99 99 99", CountryPhoneCode:"+226 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "BG", Name: "Bulgaria", FlagCssClass: "flag-bg", InputMasking: "999 999 999", CountryPhoneCode:"+359 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BH", Name: "Bahrain", FlagCssClass: "flag-bh", InputMasking: "9999 9999", CountryPhoneCode:"+973 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BI", Name: "Burundi", FlagCssClass: "flag-bi", InputMasking: "99 99 99 99", CountryPhoneCode:"+257 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BJ", Name: "Benin", FlagCssClass: "flag-bj", InputMasking: "99 99 99 99", CountryPhoneCode:"+229 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BL", Name: "Saint Barthelemy", FlagCssClass: "flag-bl", InputMasking: "9999 99 99 99", CountryPhoneCode:"+590 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BM", Name: "Bermuda", FlagCssClass: "flag-bm", InputMasking: "999-9999", CountryPhoneCode:"+1 (441) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BN", Name: "Brunei", FlagCssClass: "flag-bn", InputMasking: "999 9999", CountryPhoneCode:"+673 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BO", Name: "Bolivia", FlagCssClass: "flag-bo", InputMasking: "99999999", CountryPhoneCode:"+591 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BR", Name: "Brazil", FlagCssClass: "flag-br", InputMasking: "(99) 99999-9999", CountryPhoneCode:"+55 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BS", Name: "Bahamas", FlagCssClass: "flag-bs", InputMasking: "999-9999", CountryPhoneCode:"+1 (242) ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "BT", Name: "Bhutan", FlagCssClass: "flag-bt", InputMasking: "99 99 99 99", CountryPhoneCode:"+975 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BW", Name: "Botswana", FlagCssClass: "flag-bw", InputMasking: "99 999 999", CountryPhoneCode:"+267 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BY", Name: "Belarus", FlagCssClass: "flag-by", InputMasking: "9 999 999-99-99", CountryPhoneCode:"+375 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "BZ", Name: "Belize", FlagCssClass: "flag-bz", InputMasking: "999-9999", CountryPhoneCode:"+501 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CA", Name: "Canada", FlagCssClass: "flag-ca", InputMasking: "(999) 999-9999", CountryPhoneCode:"+1 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CC", Name: "Cocos Islands", FlagCssClass: "flag-cc", InputMasking: "9999 999 999", CountryPhoneCode:"+61 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CD", Name: "Democratic Republic of the Congo", FlagCssClass: "flag-cd", InputMasking: "9999 999 999", CountryPhoneCode:"+243 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CF", Name: "Central African Republic", FlagCssClass: "flag-cf", InputMasking: "99 99 99 99", CountryPhoneCode:"+236 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CG", Name: "Republic of the Congo", FlagCssClass: "flag-cg", InputMasking: " 99 999 9999", CountryPhoneCode:"+242 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CH", Name: "Switzerland", FlagCssClass: "flag-ch", InputMasking: "999 999 99 99", CountryPhoneCode:"+41 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "CI", Name: "Ivory Coast", FlagCssClass: "flag-ci", InputMasking: "99 99 99 99", CountryPhoneCode:"+225 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CK", Name: "Cook Islands", FlagCssClass: "flag-ck", InputMasking: "99 9999", CountryPhoneCode:"+682 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CL", Name: "Chile", FlagCssClass: "flag-cl", InputMasking: "9 9999 9999", CountryPhoneCode:"+56 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CM", Name: "Cameroon", FlagCssClass: "flag-cm", InputMasking: "9 99 99 99 99", CountryPhoneCode:"+237 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CN", Name: "China", FlagCssClass: "flag-cn", InputMasking: "999 9999 9999", CountryPhoneCode:"+86 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CO", Name: "Colombia", FlagCssClass: "flag-co", InputMasking: "999 9999999", CountryPhoneCode:"+57 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CR", Name: "Costa Rica", FlagCssClass: "flag-cr", InputMasking: "9999 9999", CountryPhoneCode:"+506 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CU", Name: "Cuba", FlagCssClass: "flag-cu", InputMasking: "99 9999999", CountryPhoneCode:"+53 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CV", Name: "Cape Verde", FlagCssClass: "flag-cv", InputMasking: "999 99 99", CountryPhoneCode:"+238 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CW", Name: "Curacao", FlagCssClass: "flag-cw", InputMasking: "999 9999", CountryPhoneCode:"+599 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "CX", Name: "Christmas Island", FlagCssClass: "flag-cx", InputMasking: "9999 999 999", CountryPhoneCode:"+61 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CY", Name: "Cyprus", FlagCssClass: "flag-cy", InputMasking: "99 999999", CountryPhoneCode:"+357 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "CZ", Name: "Czech Republic", FlagCssClass: "flag-cz", InputMasking: "999 999 999", CountryPhoneCode:"+420 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "DE", Name: "Germany", FlagCssClass: "flag-de", InputMasking: "99999 9999999", CountryPhoneCode:"+49 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "DJ", Name: "Djibouti", FlagCssClass: "flag-dj", InputMasking: "99 99 99 99", CountryPhoneCode:"+253 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "DK", Name: "Denmark", FlagCssClass: "flag-dk", InputMasking: "99 99 99 99", CountryPhoneCode:"+45 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "DM", Name: "Dominica", FlagCssClass: "flag-dm", InputMasking: "999-9999", CountryPhoneCode:"+1 (767) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "DO", Name: "Dominican Republic", FlagCssClass: "flag-do", InputMasking: "999-9999", CountryPhoneCode:"+1 (809) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "DZ", Name: "Algeria", FlagCssClass: "flag-dz", InputMasking: "9999 99 99 99", CountryPhoneCode:"+213 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "EC", Name: "Ecuador", FlagCssClass: "flag-ec", InputMasking: "999 999 9999", CountryPhoneCode:"+593 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "EE", Name: "Estonia", FlagCssClass: "flag-ee", InputMasking: "9999 9999", CountryPhoneCode:"+372 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "EG", Name: "Egypt", FlagCssClass: "flag-eg", InputMasking: "9999 999 9999", CountryPhoneCode:"+20 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "EH", Name: "Western Sahara", FlagCssClass: "flag-eh", InputMasking: "9999-999999", CountryPhoneCode:"+212 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ER", Name: "Eritrea", FlagCssClass: "flag-er", InputMasking: "99 999 999", CountryPhoneCode:"+291 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ES", Name: "Spain", FlagCssClass: "flag-es", InputMasking: "999 99 99 99", CountryPhoneCode:"+34 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ET", Name: "Ethiopia", FlagCssClass: "flag-et", InputMasking: "999 999 9999", CountryPhoneCode:"+251 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "FI", Name: "Finland", FlagCssClass: "flag-fi", InputMasking: "999 9999999", CountryPhoneCode:"+358 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "FJ", Name: "Fiji", FlagCssClass: "flag-fj", InputMasking: "999 9999", CountryPhoneCode:"+679 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "FK", Name: "Falkland Islands", FlagCssClass: "flag-fk", InputMasking: "99999", CountryPhoneCode:"+500 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "FM", Name: "Micronesia", FlagCssClass: "flag-fm", InputMasking: "999 9999", CountryPhoneCode:"+691 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "FO", Name: "Faroe Islands", FlagCssClass: "flag-fo", InputMasking: "999999", CountryPhoneCode:"+298 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "FR", Name: "France", FlagCssClass: "flag-fr", InputMasking: "99 99 99 99 99", CountryPhoneCode:"+33 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GA", Name: "Gabon", FlagCssClass: "flag-ga", InputMasking: "99 99 99 99", CountryPhoneCode:"+241 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GB", Name: "United Kingdom", FlagCssClass: "flag-gb", InputMasking: "99999 99999", CountryPhoneCode:"+44 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GD", Name: "Grenada", FlagCssClass: "flag-gd", InputMasking: "999-9999", CountryPhoneCode:"+1 (473) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GE", Name: "Georgia", FlagCssClass: "flag-ge", InputMasking: "999 99 99 99", CountryPhoneCode:"+995 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GG", Name: "Guernsey", FlagCssClass: "flag-gg", InputMasking: "99999 999999", CountryPhoneCode:"+44 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GH", Name: "Ghana", FlagCssClass: "flag-gh", InputMasking: "999 999 9999", CountryPhoneCode:"+233 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GI", Name: "Gibraltar", FlagCssClass: "flag-gi", InputMasking: "99999999", CountryPhoneCode:"+350 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GL", Name: "Greenland", FlagCssClass: "flag-gl", InputMasking: "99 99 99", CountryPhoneCode:"+299 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GM", Name: "Gambia", FlagCssClass: "flag-gm", InputMasking: "999 9999", CountryPhoneCode:"+220 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GN", Name: "Guinea", FlagCssClass: "flag-gn", InputMasking: "999 99 99 99", CountryPhoneCode:"+224 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GQ", Name: "Equatorial Guinea", FlagCssClass: "flag-gq", InputMasking: "999 999 999", CountryPhoneCode:"+240 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GR", Name: "Greece", FlagCssClass: "flag-gr", InputMasking: "999 999 9999", CountryPhoneCode:"+30 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GT", Name: "Guatemala", FlagCssClass: "flag-gt", InputMasking: "9999 9999", CountryPhoneCode:"+502 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GU", Name: "Guam", FlagCssClass: "flag-gu", InputMasking: "999-9999", CountryPhoneCode:"+1 (671) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GW", Name: "Guinea-Bissau", FlagCssClass: "flag-gw", InputMasking: "999 999 999", CountryPhoneCode:"+245 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "GY", Name: "Guyana", FlagCssClass: "flag-gy", InputMasking: "999 9999", CountryPhoneCode:"+592 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "HK", Name: "Hong Kong", FlagCssClass: "flag-hk", InputMasking: "9999 9999", CountryPhoneCode:"+852 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "HN", Name: "Honduras", FlagCssClass: "flag-hn", InputMasking: "9999-9999", CountryPhoneCode:"+504 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "HR", Name: "Croatia", FlagCssClass: "flag-hr", InputMasking: "999 999 9999", CountryPhoneCode:"+385 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "HT", Name: "Haiti", FlagCssClass: "flag-ht", InputMasking: "99 99 9999", CountryPhoneCode:"+509 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "HU", Name: "Hungary", FlagCssClass: "flag-hu", InputMasking: "(99) 999 9999", CountryPhoneCode:"+36 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ID", Name: "Indonesia", FlagCssClass: "flag-id", InputMasking: "9999-999-999", CountryPhoneCode:"+62 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IE", Name: "Ireland", FlagCssClass: "flag-ie", InputMasking: "999 999 9999", CountryPhoneCode:"+353 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IL", Name: "Israel", FlagCssClass: "flag-il", InputMasking: "999-999-9999", CountryPhoneCode:"+972 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IM", Name: "Isle of Man", FlagCssClass: "flag-im", InputMasking: "99999 999999", CountryPhoneCode:"+44 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IN", Name: "India", FlagCssClass: "flag-in", InputMasking: "99999 99999", CountryPhoneCode:"+91 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IO", Name: "British Indian Ocean Territory", FlagCssClass: "flag-io", InputMasking: "999 9999", CountryPhoneCode:"+246 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IQ", Name: "Iraq", FlagCssClass: "flag-iq", InputMasking: "9999 999 9999", CountryPhoneCode:"+964 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IR", Name: "Iran", FlagCssClass: "flag-ir", InputMasking: "9999 999 9999", CountryPhoneCode:"+98 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IS", Name: "Iceland", FlagCssClass: "flag-is", InputMasking: "999 9999", CountryPhoneCode:"+354 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "IT", Name: "Italy", FlagCssClass: "flag-it", InputMasking: "999 999 9999", CountryPhoneCode:"+39 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "JE", Name: "Jersey", FlagCssClass: "flag-je", InputMasking: "99999 999999", CountryPhoneCode:"+44 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "JM", Name: "Jamaica", FlagCssClass: "flag-jm", InputMasking: "999-9999", CountryPhoneCode:"+1 (876) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "JO", Name: "Jordan", FlagCssClass: "flag-jo", InputMasking: "99 9999 9999", CountryPhoneCode:"+962 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "JP", Name: "Japan", FlagCssClass: "flag-jp", InputMasking: "999 9999-9999", CountryPhoneCode:"+81 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "KE", Name: "Kenya", FlagCssClass: "flag-ke", InputMasking: "9999 999999", CountryPhoneCode:"+254 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KG", Name: "Kyrgyzstan", FlagCssClass: "flag-kg", InputMasking: "9999 999 999", CountryPhoneCode:"+996 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KH", Name: "Cambodia", FlagCssClass: "flag-kh", InputMasking: "999 999 999", CountryPhoneCode:"+855 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KI", Name: "Kiribati", FlagCssClass: "flag-ki", InputMasking: "99999999", CountryPhoneCode:"+686 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KM", Name: "Comoros", FlagCssClass: "flag-km", InputMasking: "999 99 99", CountryPhoneCode:"+269 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KN", Name: "Saint Kitts and Nevis", FlagCssClass: "flag-kn", InputMasking: "999-9999", CountryPhoneCode:"+1 (869) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KP", Name: "North Korea", FlagCssClass: "flag-kp", InputMasking: "9999 999 9999", CountryPhoneCode:"+850 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KR", Name: "South Korea", FlagCssClass: "flag-kr", InputMasking: "999-9999-9999", CountryPhoneCode:"+82 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KW", Name: "Kuwait", FlagCssClass: "flag-kw", InputMasking: "999 99999", CountryPhoneCode:"+965 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KY", Name: "Cayman Islands", FlagCssClass: "flag-ky", InputMasking: "999-9999", CountryPhoneCode:"+1 (345) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "KZ", Name: "Kazakhstan", FlagCssClass: "flag-kz", InputMasking: "9 (999) 999 9999", CountryPhoneCode:"+7 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LA", Name: "Laos", FlagCssClass: "flag-la", InputMasking: "999 99 999 999", CountryPhoneCode:"+856 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LB", Name: "Lebanon", FlagCssClass: "flag-lb", InputMasking: "99 999 999", CountryPhoneCode:"+961 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LC", Name: "Saint Lucia", FlagCssClass: "flag-lc", InputMasking: "999-9999", CountryPhoneCode:"+1 (758) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LI", Name: "Liechtenstein", FlagCssClass: "flag-li", InputMasking: "999 999 999", CountryPhoneCode:"+423 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LK", Name: "Sri Lanka", FlagCssClass: "flag-lk", InputMasking: "999 999 9999", CountryPhoneCode:"+94 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LR", Name: "Liberia", FlagCssClass: "flag-lr", InputMasking: "999 999 9999", CountryPhoneCode:"+231 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LS", Name: "Lesotho", FlagCssClass: "flag-ls", InputMasking: "9999 9999", CountryPhoneCode:"+266 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LT", Name: "Lithuania", FlagCssClass: "flag-lt", InputMasking: "(9-999) 99999", CountryPhoneCode:"+370 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "LU", Name: "Luxembourg", FlagCssClass: "flag-lu", InputMasking: "999 999 999", CountryPhoneCode:"+352 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LV", Name: "Latvia", FlagCssClass: "flag-lv", InputMasking: "99 999 999", CountryPhoneCode:"+371 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "LY", Name: "Libya", FlagCssClass: "flag-ly", InputMasking: "999-9999999", CountryPhoneCode:"+218 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MA", Name: "Morocco", FlagCssClass: "flag-ma", InputMasking: "9999-999999", CountryPhoneCode:"+212 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MC", Name: "Monaco", FlagCssClass: "flag-mc", InputMasking: "99 99 99 99 99", CountryPhoneCode:"+377 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MD", Name: "Moldova", FlagCssClass: "flag-md", InputMasking: "9999 99 999", CountryPhoneCode:"+373 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ME", Name: "Montenegro", FlagCssClass: "flag-me", InputMasking: "999 999 999", CountryPhoneCode:"+382 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MF", Name: "Saint Martin", FlagCssClass: "flag-mf", InputMasking: "9999 99 99 99", CountryPhoneCode:"+590 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MG", Name: "Madagascar", FlagCssClass: "flag-mg", InputMasking: "999 99 999 99", CountryPhoneCode:"+261 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MH", Name: "Marshall Islands", FlagCssClass: "flag-mh", InputMasking: "999-9999", CountryPhoneCode:"+692 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MK", Name: "Macedonia", FlagCssClass: "flag-mk", InputMasking: "999 999 999", CountryPhoneCode:"+389 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ML", Name: "Mali", FlagCssClass: "flag-ml", InputMasking: "99 99 99 99", CountryPhoneCode:"+223 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MM", Name: "Myanmar", FlagCssClass: "flag-mm", InputMasking: "99 999 9999", CountryPhoneCode:"+95 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MN", Name: "Mongolia", FlagCssClass: "flag-mn", InputMasking: "9999 9999", CountryPhoneCode:"+976 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MO", Name: "Macau", FlagCssClass: "flag-mo", InputMasking: "9999 9999", CountryPhoneCode:"+853 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MP", Name: "Northern Mariana Islands", FlagCssClass: "flag-mp", InputMasking: "999-9999", CountryPhoneCode:"+1 (670) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MR", Name: "Mauritania", FlagCssClass: "flag-mr", InputMasking: "99 99 99 99", CountryPhoneCode:"+222 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MS", Name: "Montserrat", FlagCssClass: "flag-ms", InputMasking: "999-9999", CountryPhoneCode:"+1 (664) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MT", Name: "Malta", FlagCssClass: "flag-mt", InputMasking: "9999 9999", CountryPhoneCode:"+356 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "MU", Name: "Mauritius", FlagCssClass: "flag-mu", InputMasking: "9999 9999", CountryPhoneCode:"+230 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MV", Name: "Maldives", FlagCssClass: "flag-mv", InputMasking: "999-9999", CountryPhoneCode:"+960 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MW", Name: "Malawi", FlagCssClass: "flag-mw", InputMasking: "9999 99 99 99", CountryPhoneCode:"+265 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MX", Name: "Mexico", FlagCssClass: "flag-mx", InputMasking: "999 999 999 9999", CountryPhoneCode:"+52 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MY", Name: "Malaysia", FlagCssClass: "flag-my", InputMasking: "999-999 9999", CountryPhoneCode:"+60 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "MZ", Name: "Mozambique", FlagCssClass: "flag-mz", InputMasking: "99 999 9999", CountryPhoneCode:"+258 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NA", Name: "Namibia", FlagCssClass: "flag-na", InputMasking: "999 999 9999", CountryPhoneCode:"+264 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NC", Name: "New Caledonia", FlagCssClass: "flag-nc", InputMasking: "99 99 99", CountryPhoneCode:"+687 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NE", Name: "Niger", FlagCssClass: "flag-ne", InputMasking: "99 99 99 99", CountryPhoneCode:"+227 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NG", Name: "Nigeria", FlagCssClass: "flag-ng", InputMasking: "9999 999 9999", CountryPhoneCode:"+234 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NI", Name: "Nicaragua", FlagCssClass: "flag-ni", InputMasking: "9999 9999", CountryPhoneCode:"+505 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NL", Name: "Netherlands", FlagCssClass: "flag-nl", InputMasking: "99 99999999", CountryPhoneCode:"+31 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NO", Name: "Norway", FlagCssClass: "flag-no", InputMasking: "999 99 999", CountryPhoneCode:"+47 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NP", Name: "Nepal", FlagCssClass: "flag-np", InputMasking: "999-9999999", CountryPhoneCode:"+977 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NR", Name: "Nauru", FlagCssClass: "flag-nr", InputMasking: "999 9999", CountryPhoneCode:"+674 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NU", Name: "Niue", FlagCssClass: "flag-nu", InputMasking: "999 9999", CountryPhoneCode:"+683 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "NZ", Name: "New Zealand", FlagCssClass: "flag-nz", InputMasking: "999 999 9999", CountryPhoneCode:"+64 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "OM", Name: "Oman", FlagCssClass: "flag-om", InputMasking: "9999 9999", CountryPhoneCode:"+968 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PA", Name: "Panama", FlagCssClass: "flag-pa", InputMasking: "9999-9999", CountryPhoneCode:"+507 ", IsShowCustomFlag: false });  
    CountryList.push({ ISOCode: "PE", Name: "Peru", FlagCssClass: "flag-pe", InputMasking: "999 999 999", CountryPhoneCode:"+51 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PF", Name: "French Polynesia", FlagCssClass: "flag-pf", InputMasking: "99 99 99 99", CountryPhoneCode:"+689 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PG", Name: "Papua New Guinea", FlagCssClass: "flag-pg", InputMasking: "9999 9999", CountryPhoneCode:"+675 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PH", Name: "Philippines", FlagCssClass: "flag-ph", InputMasking: "9999 999 9999", CountryPhoneCode:"+63 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PK", Name: "Pakistan", FlagCssClass: "flag-pk", InputMasking: "9999 9999999", CountryPhoneCode:"+92 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PL", Name: "Poland", FlagCssClass: "flag-pl", InputMasking: "999 999 999", CountryPhoneCode:"+48 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PM", Name: "Saint Pierre and Miquelon", FlagCssClass: "flag-pm", InputMasking: "999 99 99", CountryPhoneCode:"+508 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PN", Name: "Pitcairn", FlagCssClass: "flag-pn", InputMasking: "99 999999", CountryPhoneCode:"+64 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PR", Name: "Puerto Rico", FlagCssClass: "flag-pr", InputMasking: "999-9999", CountryPhoneCode:"+1 (787) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PS", Name: "Palestine", FlagCssClass: "flag-ps", InputMasking: "9999 999 999", CountryPhoneCode:"+970 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PT", Name: "Portugal", FlagCssClass: "flag-pt", InputMasking: "999 999 999", CountryPhoneCode:"+351 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PW", Name: "Palau", FlagCssClass: "flag-pw", InputMasking: "999 9999", CountryPhoneCode:"+680 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "PY", Name: "Paraguay", FlagCssClass: "flag-py", InputMasking: "9999 999999", CountryPhoneCode:"+595 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "QA", Name: "Qatar", FlagCssClass: "flag-qa", InputMasking: "9999 9999", CountryPhoneCode:"+974 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "RE", Name: "Reunion", FlagCssClass: "flag-re", InputMasking: "9999 99 99 99", CountryPhoneCode:"+262 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "RO", Name: "Romania", FlagCssClass: "flag-ro", InputMasking: "9999 999 999", CountryPhoneCode:"+40 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "RS", Name: "Serbia", FlagCssClass: "flag-rs", InputMasking: "999 9999999", CountryPhoneCode:"+381 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "RU", Name: "Russia", FlagCssClass: "flag-ru", InputMasking: "9 (999) 999-99-99", CountryPhoneCode:"+7 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "RW", Name: "Rwanda", FlagCssClass: "flag-rw", InputMasking: "9999 999 999", CountryPhoneCode:"+250 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SA", Name: "Saudi Arabia", FlagCssClass: "flag-sa", InputMasking: "999 999 9999", CountryPhoneCode:"+966 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SB", Name: "Solomon Islands", FlagCssClass: "flag-sb", InputMasking: "99 99999", CountryPhoneCode:"+677 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SC", Name: "Seychelles", FlagCssClass: "flag-sc", InputMasking: "9 999 999", CountryPhoneCode:"+248 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SD", Name: "Sudan", FlagCssClass: "flag-sd", InputMasking: "999 999 9999", CountryPhoneCode:"+249 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SE", Name: "Sweden", FlagCssClass: "flag-se", InputMasking: "999-999 99 99", CountryPhoneCode:"+46 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SG", Name: "Singapore", FlagCssClass: "flag-sg", InputMasking: "9999 9999", CountryPhoneCode:"+65 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SH", Name: "Saint Helena", FlagCssClass: "flag-sh", InputMasking: "99999", CountryPhoneCode:"+290 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SI", Name: "Slovenia", FlagCssClass: "flag-si", InputMasking: "999 999 999", CountryPhoneCode:"+386 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SJ", Name: "Svalbard and Jan Mayen", FlagCssClass: "flag-sj", InputMasking: "999 99 999", CountryPhoneCode:"+47 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SK", Name: "Slovakia", FlagCssClass: "flag-sk", InputMasking: "9999 999 999", CountryPhoneCode:"+421 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SL", Name: "Sierra Leone", FlagCssClass: "flag-sl", InputMasking: "(999) 999999", CountryPhoneCode:"+232 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SM", Name: "San Marino", FlagCssClass: "flag-sm", InputMasking: "99 99 99 99", CountryPhoneCode:"+378 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SN", Name: "Senegal", FlagCssClass: "flag-sn", InputMasking: "99 999 99 99", CountryPhoneCode:"+221 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SO", Name: "Somalia", FlagCssClass: "flag-so", InputMasking: "9 9999999", CountryPhoneCode:"+252 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SR", Name: "Suriname", FlagCssClass: "flag-sr", InputMasking: "999-9999", CountryPhoneCode:"+597 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SS", Name: "South Sudan", FlagCssClass: "flag-ss", InputMasking: "9999 999 999", CountryPhoneCode:"+211 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ST", Name: "Sao Tome and Principe", FlagCssClass: "flag-st", InputMasking: "999 9999", CountryPhoneCode:"+239 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SV", Name: "El Salvador", FlagCssClass: "flag-sv", InputMasking: "9999 9999", CountryPhoneCode:"+503 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SX", Name: "Sint Maarten", FlagCssClass: "flag-sx", InputMasking: "999-9999", CountryPhoneCode:"+1 (721) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SY", Name: "Syria", FlagCssClass: "flag-sy", InputMasking: "9999 999 999", CountryPhoneCode:"+963 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "SZ", Name: "Swaziland", FlagCssClass: "flag-sz", InputMasking: "9999 9999", CountryPhoneCode:"+268 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TC", Name: "Turks and Caicos Islands", FlagCssClass: "flag-tc", InputMasking: "999-9999", CountryPhoneCode:"+1 (649) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TD", Name: "Chad", FlagCssClass: "flag-td", InputMasking: "99 99 99 99", CountryPhoneCode:"+235 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TG", Name: "Togo", FlagCssClass: "flag-tg", InputMasking: "99 99 99 99", CountryPhoneCode:"+228 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TH", Name: "Thailand", FlagCssClass: "flag-th", InputMasking: "999 999 9999", CountryPhoneCode:"+66 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TJ", Name: "Tajikistan", FlagCssClass: "flag-tj", InputMasking: "999 99 9999", CountryPhoneCode:"+992 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TK", Name: "Tokelau", FlagCssClass: "flag-tk", InputMasking: "9999", CountryPhoneCode:"+690 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TL", Name: "East Timor", FlagCssClass: "flag-tl", InputMasking: "9999 9999", CountryPhoneCode:"+670 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TM", Name: "Turkmenistan", FlagCssClass: "flag-tm", InputMasking: "9 99 999999", CountryPhoneCode:"+993 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TN", Name: "Tunisia", FlagCssClass: "flag-tn", InputMasking: "99 999 999", CountryPhoneCode:"+216 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TO", Name: "Tonga", FlagCssClass: "flag-to", InputMasking: "999 9999", CountryPhoneCode:"+676 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TR", Name: "Turkey", FlagCssClass: "flag-tr", InputMasking: "9999 999 99 99", CountryPhoneCode:"+90 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TT", Name: "Trinidad and Tobago", FlagCssClass: "flag-tt", InputMasking: "999-9999", CountryPhoneCode:"+1 (868) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TV", Name: "Tuvalu", FlagCssClass: "flag-tv", InputMasking: "999999", CountryPhoneCode:"+688 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TW", Name: "Taiwan", FlagCssClass: "flag-tw", InputMasking: "9999 999 999", CountryPhoneCode:"+886 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "TZ", Name: "Tanzania", FlagCssClass: "flag-tz", InputMasking: "9999 999 999", CountryPhoneCode:"+255 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "UA", Name: "Ukraine", FlagCssClass: "flag-ua", InputMasking: "999 999 9999", CountryPhoneCode:"+380 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "UG", Name: "Uganda", FlagCssClass: "flag-ug", InputMasking: "9999 999999", CountryPhoneCode:"+256 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "US", Name: "United States", FlagCssClass: "flag-us", InputMasking: "(999) 999-9999", CountryPhoneCode:"+1 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "UY", Name: "Uruguay", FlagCssClass: "flag-uy", InputMasking: "999 999 999", CountryPhoneCode:"+598 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "UZ", Name: "Uzbekistan", FlagCssClass: "flag-uz", InputMasking: "9 99 999 99 99", CountryPhoneCode:"+998 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VA", Name: "Vatican", FlagCssClass: "flag-va", InputMasking: "999 999 9999", CountryPhoneCode:"+39 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VC", Name: "Saint Vincent and the Grenadines", FlagCssClass: "flag-vc", InputMasking: "999-9999", CountryPhoneCode:"+1 (784) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VE", Name: "Venezuela", FlagCssClass: "flag-ve", InputMasking: "9999-9999999", CountryPhoneCode:"+58 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VG", Name: "British Virgin Islands", FlagCssClass: "flag-vg", InputMasking: "999-9999", CountryPhoneCode:"+1 (284) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VI", Name: "U.S. Virgin Islands", FlagCssClass: "flag-vi", InputMasking: "999-9999", CountryPhoneCode:"+1 (340) ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VN", Name: "Vietnam", FlagCssClass: "flag-vn", InputMasking: "999 999 99 99", CountryPhoneCode:"+84 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "VU", Name: "Vanuatu", FlagCssClass: "flag-vu", InputMasking: "999 9999", CountryPhoneCode:"+678 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "WF", Name: "Wallis and Futuna", FlagCssClass: "flag-wf", InputMasking: "99 99 99", CountryPhoneCode:"+681 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "WS", Name: "Samoa", FlagCssClass: "flag-ws", InputMasking: "99 99999", CountryPhoneCode:"+685 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "XK", Name: "Kosovo", FlagCssClass: "flag-xk", InputMasking: "999 999 999", CountryPhoneCode:"+383 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "YE", Name: "Yemen", FlagCssClass: "flag-ye", InputMasking: "9999 999 999", CountryPhoneCode:"+967 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "YT", Name: "Mayotte", FlagCssClass: "flag-yt", InputMasking: "9999 99 99 99", CountryPhoneCode:"+262 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ZA", Name: "South Africa", FlagCssClass: "flag-za", InputMasking: "999 999 9999", CountryPhoneCode:"+27 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ZM", Name: "Zambia", FlagCssClass: "flag-zm", InputMasking: "999 9999999", CountryPhoneCode:"+260 ", IsShowCustomFlag: false });
    CountryList.push({ ISOCode: "ZW", Name: "Zimbabwe", FlagCssClass: "flag-zw", InputMasking: "999 999 9999", CountryPhoneCode:"+263 ", IsShowCustomFlag: false });
  
  return CountryList;
 }
}
